name: Deploy to Netlify

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-21.05
          extra_nix_config: |
            extra-platforms = aarch64-linux

      - name: Install deps
        run: nix-shell --pure --run "yarn install"

      - name: Build site
        run: nix-shell --pure --run "yarn build"

      - name: Deploy site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: nix-shell --pure --run "echo $NETLIFY_SITE_ID"
